# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ai-deployemnts-ajay"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    key            = "environments/dev/terraform.tfstate"
    region         = "us-east-1"
  }
}
