# Development Environment Providers
# This file is generated by Terragrunt from the root configuration

# The provider configuration is automatically generated by Terragrunt
# based on the root terragrunt.hcl file. No additional configuration needed here.